class Page78_79 {
  static String getTextContent() {
    return """
"Of course I noticed the self-distancing in her first sentence. Don't hurt him. My eyes instantly cleared. I knew instantly that she was part of the conspiracy. She was the bait used to lure susceptible men into dark alleys. But my realization helped me nothing since I was held at the point of a gun.
"The only thing I could say was from God we came and unto Him is our returning. This is the standard prayer in the face of any calamity. I kept reciting that till the man with the gun shouted at me to stop or he would waste me. I was shivering from head to foot. But they did not notice. The man's vocabulary seemed to consist of only one word, waste. I was instinctively beginning to have a wasteful idea myself.
"He instructed his companion whom he addressed as Roger to start the car. Strangely enough the car would not start. He did his best but the car would not start.    
"They did all they could but the car would not budge. Obviously it was the car they wanted. But I was also sure they would not hesitate to shoot me if I gave them the slightest opportunity. When the car refused to pick after the third attempt, I was asked to start it.
"I was bemused to see that when I sat behind the driving wheel, I touched the gear lever and discovered that it was still engaged. Since the car was an automatic transmission, the ignition would not pick so long as the gear is engaged. But I was still rattled, thinking for a way out without getting myself killed. Meanwhile, the robber with the gun kept threatening me to start the car or he would splash my brains across the dashboard and the windshield. I returned the lever to Park and turned on the ignition. The car started. Then I was ordered to come back to the back seat while the other fellow drove. He went and sat behind the wheel and attempted to engage gear. Again the gear lever proved uncooperative. Tried as he
could, the car would not move. 'Let this lover boy drive the car himself to the office.'
"I did not know what they were talking about. But from the moment I once again sat behind the wheel, there was only one thought; escape or death. I started driving slowly then when I came near another turn which they said led to their office    
and instructed me to take that turn, I ignored them. The man with the gun kept threatening he would waste me if I did not turn. Impulsively, I decided to waste all of us in the car. I pressed hard on the accelerator pedal and the car gathered momentum and flew ahead. I did not stop till I came to an intersection about three hundred metres later.
My stopping was not borne out of any rational decision to obey traffic regulation. Indeed, at that moment when I neared the intersection, I did not know whether I was the one on the narrow road linking to the major road or vice versa. The very self-preservation instinct that made me to drive at such a break-neck speed with the robbers inside the car was the same impulsive decision that made me to pause and look if there was a vehicle coming from my either side. I swerved to the right when I saw that the only vehicle coming was from my left. As I swerved, my right front wheel got momentarily stuck in the mud but I accelerated and it became unstuck. While this was going on, I looked to my right and discovered that the man wielding the gun earlier had disappeared from the vehicle. I turned around. There was nobody at the back seat either. Roger and Natasha seemed to have disappeared into thin air.
                                                          
""";
  }
}
